import 'failures.dart';

/// AF 2021-05-08 temp remove while doing null safe conversion
// class NotAuthenticatedError extends Error {}

// class UnexpectedValueError extends Error {
//   final ValueFailure valueFailure;

//   UnexpectedValueError(this.valueFailure);

//   @override
//   String toString() {
//     const explanation =
//         'Encountered a ValueFailure at an unrecoverable point. Terminating.';
//     return Error.safeToString('$explanation Failure was: $valueFailure');
//   }
// }
